#!/usr/bin/env python3
"""
CHASEDB1 deep-supervision lambda grid training.

Default paths:
  data:   ./data/CHASEDB1
  models: ./models/chase
"""

import os
import json
import argparse
from datetime import datetime
from pathlib import Path
import random

import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F
from tqdm import tqdm
import matplotlib.pyplot as plt

from improved_pdc_convolutions import normalize_config_string
from pdc_unet_model import create_model
from path_compat import apply_model_path_aliases

try:
    import cv2
except Exception:
    cv2 = None

try:
    from PIL import Image
except Exception:
    Image = None

_ALLOWED_EXTS = {".png", ".tif", ".tiff", ".jpg", ".jpeg", ".bmp"}

_IMG_CACHE = {}
_MASK_CACHE = {}
_FOV_CACHE = {}


def _read_gray(path: str) -> np.ndarray:
    if cv2 is not None:
        img = cv2.imread(path, cv2.IMREAD_UNCHANGED)
        if img is None:
            raise FileNotFoundError(f"Failed to read: {path}")
        if img.ndim == 3:
            img = img[:, :, 1]
        img = img.astype(np.float32)
    else:
        if Image is None:
            raise ImportError("Missing cv2 or PIL, cannot read images.")
        img = np.array(Image.open(path))
        if img.ndim == 3:
            img = img[:, :, 1]
        img = img.astype(np.float32)

    if img.max() > 1.0:
        img /= 255.0
    return img


def _read_mask(path: str) -> np.ndarray:
    m = _read_gray(path)
    return (m > 0.5).astype(np.float32)


def _list_files(folder: str):
    p = Path(folder)
    if not p.exists():
        return []
    files = [str(x) for x in p.iterdir() if x.is_file() and x.suffix.lower() in _ALLOWED_EXTS]
    files.sort()
    return files


def _find_subdir(root: str, candidates):
    for c in candidates:
        d = os.path.join(root, c)
        if os.path.isdir(d):
            return d
    return None


def _compute_fov_mask(img: np.ndarray, thresh: float = 0.05, blur_ksize: int = 7, close_ksize: int = 15):
    """Autogenerated docstring."""
    if img is None:
        return None
    m = img.copy()
    if cv2 is not None and blur_ksize and blur_ksize > 0:
        k = int(blur_ksize)
        if k % 2 == 0:
            k += 1
        m = cv2.GaussianBlur(m, (k, k), 0)

    mask = (m > float(thresh)).astype(np.uint8)

    if cv2 is not None and close_ksize and close_ksize > 0:
        k = int(close_ksize)
        if k % 2 == 0:
            k += 1
        kernel = cv2.getStructuringElement(cv2.MORPH_ELLIPSE, (k, k))
        mask = cv2.morphologyEx(mask, cv2.MORPH_CLOSE, kernel)

    return mask.astype(np.float32)


def _candidate_mask_stems(image_stem: str, mask_type: str = "auto"):
    mask_type = (mask_type or "auto").lower()
    if mask_type not in ("1stho", "2ndho", "auto"):
        mask_type = "auto"
    if mask_type == "1stho":
        suffixes = ["1stHO"]
    elif mask_type == "2ndho":
        suffixes = ["2ndHO"]
    else:
        suffixes = ["1stHO", "2ndHO"]

    cands = []
    if "_rot" in image_stem:
        base, rot = image_stem.rsplit("_rot", 1)
        for suf in suffixes:
            cands.append(f"{base}_rot{rot}_{suf}")
            cands.append(f"{base}_{suf}_rot{rot}")
            cands.append(f"{image_stem}_{suf}")
    else:
        for suf in suffixes:
            cands.append(f"{image_stem}_{suf}")
    cands.append(image_stem)
    return cands


def _pair_images_and_masks(im_dir: str, mask_dir: str, mask_type: str = "auto"):
    im_files = _list_files(im_dir)
    if not im_files:
        raise RuntimeError(f"No images found: {im_dir}")

    mask_map = {}
    for m in _list_files(mask_dir):
        mask_map[Path(m).stem] = m

    pairs = []
    missing = []
    for im in im_files:
        stem = Path(im).stem
        mp = None
        for cand in _candidate_mask_stems(stem, mask_type=mask_type):
            if cand in mask_map:
                mp = mask_map[cand]
                break
        if mp is None:
            cand = os.path.join(mask_dir, f"{stem}.png")
            if os.path.exists(cand):
                mp = cand
        if mp is None:
            missing.append(Path(im).name)
            continue
        pairs.append((im, mp))

    if missing:
        print(f"[Warn] {len(missing)} images have no matching mask, e.g.: {missing[:5]}")
    if not pairs:
        raise RuntimeError("No image/mask pairs found. Check train/im and train/label naming.")
    return pairs


class PatchDataset(torch.utils.data.Dataset):
    def __init__(
        self,
        pairs,
        patch_size=48,
        stride=16,
        min_foreground_ratio: float = 0.0,
        augment: bool = True,
        brightness_range=(0.8, 1.2),
        contrast_range=(0.8, 1.2),
        use_fov_mask: bool = False,
        fov_threshold: float = 0.05,
        fov_blur: int = 7,
        fov_close: int = 15,
        fov_min_ratio: float = 0.0,
    ):
        self.pairs = pairs
        self.patch_size = int(patch_size)
        self.stride = int(stride)
        self.min_foreground_ratio = float(min_foreground_ratio)
        self.augment = bool(augment)
        self.brightness_range = brightness_range
        self.contrast_range = contrast_range
        self.use_fov_mask = bool(use_fov_mask)
        self.fov_threshold = float(fov_threshold)
        self.fov_blur = int(fov_blur)
        self.fov_close = int(fov_close)
        self.fov_min_ratio = float(fov_min_ratio)

        self.index = []
        for idx, (im_path, mask_path) in enumerate(self.pairs):
            h, w = self._get_hw(im_path)
            ps = self.patch_size
            st = self.stride
            if h < ps or w < ps:
                continue
            fov = None
            if self.use_fov_mask and self.fov_min_ratio > 0.0:
                if im_path not in _IMG_CACHE:
                    _IMG_CACHE[im_path] = _read_gray(im_path)
                if im_path not in _FOV_CACHE:
                    _FOV_CACHE[im_path] = _compute_fov_mask(
                        _IMG_CACHE[im_path],
                        thresh=self.fov_threshold,
                        blur_ksize=self.fov_blur,
                        close_ksize=self.fov_close,
                    )
                fov = _FOV_CACHE.get(im_path, None)
            if self.min_foreground_ratio > 0.0:
                mask = _read_mask(mask_path)
                for y in range(0, h - ps + 1, st):
                    for x in range(0, w - ps + 1, st):
                        if fov is not None and fov[y:y + ps, x:x + ps].mean() < self.fov_min_ratio:
                            continue
                        if mask[y:y + ps, x:x + ps].mean() >= self.min_foreground_ratio:
                            self.index.append((idx, y, x))
            else:
                for y in range(0, h - ps + 1, st):
                    for x in range(0, w - ps + 1, st):
                        if fov is not None and fov[y:y + ps, x:x + ps].mean() < self.fov_min_ratio:
                            continue
                        self.index.append((idx, y, x))

        if not self.index:
            raise RuntimeError("Empty patch index. Check image sizes and patch_size.")

    def _get_hw(self, im_path: str):
        if Image is not None:
            with Image.open(im_path) as im:
                w, h = im.size
            return h, w
        if cv2 is not None:
            img = cv2.imread(im_path, cv2.IMREAD_UNCHANGED)
            if img is None:
                raise FileNotFoundError(im_path)
            return img.shape[0], img.shape[1]
        raise ImportError("Missing cv2 or PIL, cannot read image size.")

    def __len__(self):
        return len(self.index)

    def _apply_augmentation(self, image, mask):
        if random.random() > 0.5:
            k = random.randint(1, 3)
            image = np.rot90(image, k).copy()
            mask = np.rot90(mask, k).copy()

        if random.random() > 0.5:
            image = np.fliplr(image).copy()
            mask = np.fliplr(mask).copy()

        if random.random() > 0.5:
            image = np.flipud(image).copy()
            mask = np.flipud(mask).copy()

        if random.random() > 0.5:
            lo, hi = self.brightness_range
            factor = random.uniform(lo, hi)
            image = np.clip(image * factor, 0, 1)

        if random.random() > 0.5:
            lo, hi = self.contrast_range
            alpha = random.uniform(lo, hi)
            image = np.clip((image - 0.5) * alpha + 0.5, 0, 1)

        return image, mask

    def __getitem__(self, i):
        img_idx, y, x = self.index[i]
        im_path, mask_path = self.pairs[img_idx]

        if im_path not in _IMG_CACHE:
            _IMG_CACHE[im_path] = _read_gray(im_path)
        if mask_path not in _MASK_CACHE:
            _MASK_CACHE[mask_path] = _read_mask(mask_path)
        if self.use_fov_mask and im_path not in _FOV_CACHE:
            _FOV_CACHE[im_path] = _compute_fov_mask(
                _IMG_CACHE[im_path],
                thresh=self.fov_threshold,
                blur_ksize=self.fov_blur,
                close_ksize=self.fov_close,
            )

        img = _IMG_CACHE[im_path]
        msk = _MASK_CACHE[mask_path]

        ps = self.patch_size
        img_patch = img[y:y + ps, x:x + ps]
        msk_patch = msk[y:y + ps, x:x + ps]
        if self.use_fov_mask:
            fov = _FOV_CACHE.get(im_path, None)
            if fov is not None:
                fov_patch = fov[y:y + ps, x:x + ps]
                img_patch = img_patch * fov_patch
                msk_patch = msk_patch * fov_patch

        if self.augment:
            img_patch, msk_patch = self._apply_augmentation(img_patch, msk_patch)

        img_t = torch.from_numpy(img_patch[None, ...].astype(np.float32))
        msk_t = torch.from_numpy(msk_patch[None, ...].astype(np.float32))
        return img_t, msk_t


def get_data_loaders_chase(data_dir, batch_size=16, patch_size=48, stride=16,
                           num_workers=4, seed=42, val_ratio=0.2,
                           min_foreground_ratio: float = 0.0,
                           mask_type: str = "auto",
                           augment: bool = True,
                           brightness_range=(0.8, 1.2),
                           contrast_range=(0.8, 1.2),
                           use_fov_mask: bool = False,
                           fov_threshold: float = 0.05,
                           fov_blur: int = 7,
                           fov_close: int = 15,
                           fov_min_ratio: float = 0.0):
    train_root = os.path.join(data_dir, "train")
    val_root = os.path.join(data_dir, "validate")

    train_im_dir = _find_subdir(train_root, ["im", "image", "images"])
    train_lb_dir = _find_subdir(train_root, ["label", "labels"])
    if train_im_dir is None or train_lb_dir is None:
        raise RuntimeError(f"CHASEDB1/train missing im or label folder: {train_root}")

    train_pairs_all = _pair_images_and_masks(train_im_dir, train_lb_dir, mask_type=mask_type)

    val_im_dir = _find_subdir(val_root, ["im", "image", "images"])
    val_lb_dir = _find_subdir(val_root, ["label", "labels"])
    val_pairs = []
    if val_im_dir and val_lb_dir:
        if len(_list_files(val_im_dir)) > 0 and len(_list_files(val_lb_dir)) > 0:
            val_pairs = _pair_images_and_masks(val_im_dir, val_lb_dir, mask_type=mask_type)

    if not val_pairs:
        rng = np.random.RandomState(seed)
        n = len(train_pairs_all)
        idx = np.arange(n)
        rng.shuffle(idx)
        n_val = max(1, int(round(n * val_ratio)))
        val_idx = set(idx[:n_val].tolist())
        train_pairs = [train_pairs_all[i] for i in range(n) if i not in val_idx]
        val_pairs = [train_pairs_all[i] for i in range(n) if i in val_idx]
    else:
        train_pairs = train_pairs_all

    train_ds = PatchDataset(
        train_pairs,
        patch_size=patch_size,
        stride=stride,
        min_foreground_ratio=min_foreground_ratio,
        augment=augment,
        brightness_range=brightness_range,
        contrast_range=contrast_range,
        use_fov_mask=use_fov_mask,
        fov_threshold=fov_threshold,
        fov_blur=fov_blur,
        fov_close=fov_close,
        fov_min_ratio=fov_min_ratio,
    )
    val_ds = PatchDataset(
        val_pairs,
        patch_size=patch_size,
        stride=stride,
        min_foreground_ratio=min_foreground_ratio,
        augment=False,
        brightness_range=brightness_range,
        contrast_range=contrast_range,
        use_fov_mask=use_fov_mask,
        fov_threshold=fov_threshold,
        fov_blur=fov_blur,
        fov_close=fov_close,
        fov_min_ratio=fov_min_ratio,
    )

    train_loader = torch.utils.data.DataLoader(
        train_ds, batch_size=batch_size, shuffle=True,
        num_workers=num_workers, pin_memory=True, drop_last=False
    )
    val_loader = torch.utils.data.DataLoader(
        val_ds, batch_size=batch_size, shuffle=False,
        num_workers=num_workers, pin_memory=True, drop_last=False
    )
    return train_loader, val_loader


class DiceLoss(nn.Module):
    def __init__(self, smooth=1e-6):
        super().__init__()
        self.smooth = smooth

    def forward(self, pred, target):
        pred = pred.contiguous()
        target = target.contiguous()
        intersection = (pred * target).sum(dim=2).sum(dim=2)
        dice = (2. * intersection + self.smooth) / (
            pred.sum(dim=2).sum(dim=2) +
            target.sum(dim=2).sum(dim=2) +
            self.smooth
        )
        return 1 - dice.mean()


class CombinedLoss(nn.Module):
    def __init__(self, bce_weight=0.5, dice_weight=0.5):
        super().__init__()
        self.bce_weight = bce_weight
        self.dice_weight = dice_weight
        self.bce = nn.BCELoss()
        self.dice = DiceLoss()

    def forward(self, pred, target):
        bce_loss = self.bce(pred, target)
        dice_loss = self.dice(pred, target)
        return self.bce_weight * bce_loss + self.dice_weight * dice_loss

class TverskyLoss(nn.Module):
    def __init__(self, alpha=0.7, beta=0.3, smooth=1e-6):
        super().__init__()
        self.alpha = alpha
        self.beta = beta
        self.smooth = smooth

    def forward(self, pred, target):
        pred = pred.contiguous()
        target = target.contiguous()
        tp = (pred * target).sum(dim=2).sum(dim=2)
        fp = (pred * (1 - target)).sum(dim=2).sum(dim=2)
        fn = ((1 - pred) * target).sum(dim=2).sum(dim=2)
        tversky = (tp + self.smooth) / (tp + self.alpha * fp + self.beta * fn + self.smooth)
        return 1 - tversky.mean()


class FocalTverskyLoss(nn.Module):
    def __init__(self, alpha=0.7, beta=0.3, gamma=1.33, smooth=1e-6):
        super().__init__()
        self.alpha = alpha
        self.beta = beta
        self.gamma = gamma
        self.smooth = smooth

    def forward(self, pred, target):
        pred = pred.contiguous()
        target = target.contiguous()
        tp = (pred * target).sum(dim=2).sum(dim=2)
        fp = (pred * (1 - target)).sum(dim=2).sum(dim=2)
        fn = ((1 - pred) * target).sum(dim=2).sum(dim=2)
        tversky = (tp + self.smooth) / (tp + self.alpha * fp + self.beta * fn + self.smooth)
        loss = (1 - tversky) ** self.gamma
        return loss.mean()


def count_parameters(model):
    return sum(p.numel() for p in model.parameters())


def set_random_seed(seed: int):
    print(f"Set random seed: {seed}")
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False


def compute_deep_supervision_loss(outputs, targets, criterion, lambda_ds: float):
    if isinstance(outputs, (tuple, list)) and len(outputs) == 3:
        p0, p1, p2 = outputs
    else:
        p0 = outputs
        p1, p2 = None, None

    loss0 = criterion(p0, targets)
    if lambda_ds <= 0.0 or p1 is None or p2 is None:
        return loss0

    target_size = targets.shape[2:]
    p1_up = F.interpolate(p1, size=target_size, mode='bilinear', align_corners=False)
    p2_up = F.interpolate(p2, size=target_size, mode='bilinear', align_corners=False)

    loss1 = criterion(p1_up, targets)
    loss2 = criterion(p2_up, targets)

    return loss0 + lambda_ds * (loss1 + 0.5 * loss2)


def train_epoch(model, dataloader, criterion, optimizer, device,
                epoch, lambda_ds: float, exp_name: str):
    model.train()
    total_loss = 0.0
    num_batches = len(dataloader)

    progress_bar = tqdm(dataloader, desc=f'{exp_name} - Epoch {epoch}')
    for batch_idx, (images, masks) in enumerate(progress_bar):
        images = images.to(device, non_blocking=True)
        masks = masks.to(device, non_blocking=True)

        optimizer.zero_grad()
        outputs = model(images)
        loss = compute_deep_supervision_loss(outputs, masks, criterion, lambda_ds)
        loss.backward()
        optimizer.step()

        total_loss += loss.item()
        progress_bar.set_postfix({
            'loss': f'{loss.item():.4f}',
            'avg_loss': f'{total_loss / (batch_idx + 1):.4f}'
        })

    return total_loss / max(1, num_batches)


def validate_epoch(model, dataloader, criterion, device, lambda_ds: float):
    model.eval()
    total_loss = 0.0
    n = len(dataloader)

    with torch.no_grad():
        for images, masks in tqdm(dataloader, desc='Validating'):
            images = images.to(device, non_blocking=True)
            masks = masks.to(device, non_blocking=True)
            outputs = model(images)
            loss = compute_deep_supervision_loss(outputs, masks, criterion, lambda_ds)
            total_loss += loss.item()

    return total_loss / max(1, n)


def plot_training_curves(history, save_dir, exp_name):
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(15, 5))
    epochs = range(1, len(history['train_loss']) + 1)

    ax1.plot(epochs, history['train_loss'], label='Training Loss')
    ax1.plot(epochs, history['val_loss'], label='Validation Loss')
    ax1.set_title(f'{exp_name} - Loss Curves')
    ax1.set_xlabel('Epoch')
    ax1.set_ylabel('Loss')
    ax1.legend()
    ax1.grid(True)

    ax2.plot(epochs, history['learning_rates'], label='Learning Rate')
    ax2.set_title(f'{exp_name} - Learning Rate')
    ax2.set_xlabel('Epoch')
    ax2.set_ylabel('Learning Rate')
    ax2.set_yscale('log')
    ax2.legend()
    ax2.grid(True)

    plt.tight_layout()
    os.makedirs(save_dir, exist_ok=True)
    fig_path = os.path.join(save_dir, 'training_curves.png')
    plt.savefig(fig_path, dpi=300, bbox_inches='tight')
    plt.close()


def train_single_lambda(lambda_ds: float, args, device, train_loader, val_loader):
    lambda_str = f"{lambda_ds:.1f}".replace('.', '_')
    lambda_dir = f"lambda_{lambda_str}"
    seed_dir = f"seed{args.seed}"

    exp_root = os.path.join(args.save_dir, lambda_dir, seed_dir)
    os.makedirs(exp_root, exist_ok=True)

    checkpoint_path = os.path.join(exp_root, 'best_model.pth')
    exp_name = f"lambda_{lambda_ds:.2f}_seed{args.seed}"

    print("\n" + "#" * 70)
    print(f"Start training: {exp_name}")
    print(f"Save dir: {exp_root}")
    print("#" * 70 + "\n")

    if os.path.exists(checkpoint_path) and (not args.overwrite):
        print(f"Found existing model: {checkpoint_path}")
        print("Skip (use --overwrite to retrain).")
        return

    model = create_model(
        config_str=args.fixed_config,
        channels=args.fixed_channels,
        use_gpdc=True,
        use_residual=False,
        use_lmm=False,
        use_sdpm=True,
        use_deep_supervision=True,
    ).to(device)

    param_count = count_parameters(model)
    print(f"Parameters: {param_count:,}")
    print(f"Train patches: {len(train_loader.dataset)}")
    print(f"Val patches: {len(val_loader.dataset)}")

    if args.loss_type == 'bce_dice':
        criterion = CombinedLoss(bce_weight=args.bce_weight, dice_weight=args.dice_weight)
    elif args.loss_type == 'tversky':
        criterion = TverskyLoss(alpha=args.tversky_alpha, beta=args.tversky_beta)
    else:
        criterion = FocalTverskyLoss(
            alpha=args.tversky_alpha,
            beta=args.tversky_beta,
            gamma=args.tversky_gamma,
        )
    optimizer = optim.Adam(
        model.parameters(),
        lr=args.learning_rate,
        weight_decay=args.weight_decay,
    )
    scheduler = optim.lr_scheduler.ReduceLROnPlateau(
        optimizer, mode='min', factor=0.5, patience=10, verbose=True
    )

    history = {
        'train_loss': [],
        'val_loss': [],
        'learning_rates': [],
        'experiment_info': {
            'lambda_ds': lambda_ds,
            'seed': args.seed,
            'config': args.fixed_config,
            'channels': args.fixed_channels,
            'use_gpdc': True,
            'use_residual': False,
            'use_lmm': False,
            'use_sdpm': True,
            'use_deep_supervision': True,
            'parameters': param_count
        }
    }

    best_val_loss = float('inf')
    patience_counter = 0
    start_time = datetime.now()

    for epoch in range(1, args.epochs + 1):
        train_loss = train_epoch(model, train_loader, criterion, optimizer,
                                 device, epoch, lambda_ds, exp_name)
        val_loss = validate_epoch(model, val_loader, criterion, device, lambda_ds)

        scheduler.step(val_loss)
        current_lr = optimizer.param_groups[0]['lr']

        history['train_loss'].append(train_loss)
        history['val_loss'].append(val_loss)
        history['learning_rates'].append(current_lr)

        print(f'Epoch {epoch:3d}: Train={train_loss:.6f}, Val={val_loss:.6f}, LR={current_lr:.2e}')

        if val_loss < best_val_loss:
            best_val_loss = val_loss
            patience_counter = 0

            torch.save({
                'epoch': epoch,
                'model_state_dict': model.state_dict(),
                'optimizer_state_dict': optimizer.state_dict(),
                'best_val_loss': best_val_loss,
                'lambda_ds': lambda_ds,
                'seed': args.seed,
                'config': args.fixed_config,
                'channels': args.fixed_channels,
                'use_gpdc': True,
                'use_residual': False,
                'use_lmm': False,
                'use_sdpm': True,
                'use_deep_supervision': True,
                'parameters': param_count,
                'args': vars(args)
            }, checkpoint_path)
            print(f'  -> saved best model (val loss: {best_val_loss:.6f})')
        else:
            patience_counter += 1

        if patience_counter >= args.patience:
            print(f'Early stop triggered after {args.patience} epochs without improvement.')
            break

    duration = datetime.now() - start_time

    history_path = os.path.join(exp_root, 'training_history.json')
    with open(history_path, 'w', encoding='utf-8') as f:
        json.dump(history, f, indent=2, ensure_ascii=False)

    plot_training_curves(history, exp_root, exp_name)

    print(f"\nTraining finished: {exp_name}")
    print(f"Best val loss: {best_val_loss:.6f}")
    print(f"Elapsed: {duration}")
    print(f"Model path: {checkpoint_path}")
    print(f"History path: {history_path}")


def parse_float_list(s: str):
    return [float(x.strip()) for x in s.split(',') if x.strip() != '']

def parse_range(s: str, default=(0.8, 1.2)):
    if s is None:
        return default
    parts = [float(x.strip()) for x in s.split(',') if x.strip() != '']
    if len(parts) == 1:
        return (parts[0], parts[0])
    if len(parts) >= 2:
        return (parts[0], parts[1])
    return default


def main():
    parser = argparse.ArgumentParser(description='CHASEDB1: lambda grid training')

    parser.add_argument('--data_dir', type=str, default='./data/CHASEDB1')
    parser.add_argument('--save_dir', type=str, default='./models/chase')
    parser.add_argument('--device', type=str, default='cuda')

    parser.add_argument('--batch_size', type=int, default=16)
    parser.add_argument('--epochs', type=int, default=30)
    parser.add_argument('--learning_rate', type=float, default=1e-4)
    parser.add_argument('--patch_size', type=int, default=96)
    parser.add_argument('--stride', type=int, default=32)
    parser.add_argument('--num_workers', type=int, default=4)
    parser.add_argument('--patience', type=int, default=20)
    parser.add_argument('--overwrite', action='store_true')
    parser.add_argument('--min_foreground_ratio', type=float, default=0.01,
                        help='Filter patches with foreground ratio lower than this (0.0 disables)')
    parser.add_argument('--mask_type', type=str, default='1stHO',
                        help='Mask type: 1stHO, 2ndHO, or auto')
    parser.add_argument('--no_augment', action='store_true',
                        help='Disable data augmentation')
    parser.add_argument('--brightness_range', type=str, default='0.8,1.2',
                        help='Brightness factor range, e.g. \"0.8,1.2\"')
    parser.add_argument('--contrast_range', type=str, default='0.8,1.2',
                        help='Contrast factor range, e.g. \"0.8,1.2\"')
    parser.add_argument('--weight_decay', type=float, default=1e-4,
                        help='Weight decay for Adam optimizer')
    parser.add_argument('--use_fov_mask', action='store_true',
                        help='Apply FOV mask during training')
    parser.add_argument('--fov_threshold', type=float, default=0.05,
                        help='FOV mask intensity threshold (0~1)')
    parser.add_argument('--fov_blur', type=int, default=7,
                        help='Gaussian blur kernel size for FOV mask (odd, 0 disables)')
    parser.add_argument('--fov_close', type=int, default=15,
                        help='Morph close kernel size for FOV mask (odd, 0 disables)')
    parser.add_argument('--fov_min_ratio', type=float, default=0.0,
                        help='Minimum FOV coverage ratio for patches (0 disables)')
    parser.add_argument('--loss_type', type=str, default='bce_dice',
                        choices=['bce_dice', 'tversky', 'focal_tversky'],
                        help='Loss type')
    parser.add_argument('--bce_weight', type=float, default=0.5)
    parser.add_argument('--dice_weight', type=float, default=0.5)
    parser.add_argument('--tversky_alpha', type=float, default=0.7,
                        help='Tversky alpha (penalize FP)')
    parser.add_argument('--tversky_beta', type=float, default=0.3,
                        help='Tversky beta (penalize FN)')
    parser.add_argument('--tversky_gamma', type=float, default=1.33,
                        help='Focal Tversky gamma')

    parser.add_argument('--lambda_ds', type=float, default=0.1)
    parser.add_argument('--grid_mode', action='store_true')
    parser.add_argument('--lambda_list', type=str,
                        default='0.0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9')

    parser.add_argument('--seed', type=int, default=42)

    parser.add_argument('--fixed_config', type=str, default='C-[V]脳11')
    parser.add_argument('--fixed_channels', type=int, default=32)

    args = parser.parse_args()
    try:
        args.fixed_config = normalize_config_string(args.fixed_config)
    except ValueError:
        args.fixed_config = "C-[V]x11"
    apply_model_path_aliases(args, ('save_dir',))

    device = torch.device(args.device if torch.cuda.is_available() else 'cpu')
    print(f"Device: {device}")

    set_random_seed(args.seed)
    os.makedirs(args.save_dir, exist_ok=True)

    augment = not args.no_augment
    brightness_range = parse_range(args.brightness_range, default=(0.8, 1.2))
    contrast_range = parse_range(args.contrast_range, default=(0.8, 1.2))

    train_loader, val_loader = get_data_loaders_chase(
        data_dir=args.data_dir,
        batch_size=args.batch_size,
        patch_size=args.patch_size,
        stride=args.stride,
        num_workers=args.num_workers,
        seed=args.seed,
        val_ratio=0.2,
        min_foreground_ratio=args.min_foreground_ratio,
        mask_type=args.mask_type,
        augment=augment,
        brightness_range=brightness_range,
        contrast_range=contrast_range,
        use_fov_mask=args.use_fov_mask,
        fov_threshold=args.fov_threshold,
        fov_blur=args.fov_blur,
        fov_close=args.fov_close,
        fov_min_ratio=args.fov_min_ratio,
    )

    print("\n" + "#" * 70)
    print("CHASEDB1 training config")
    print(f"- data_dir     : {args.data_dir}")
    print(f"- save_dir     : {args.save_dir}")
    print(f"- seed         : {args.seed}")
    print(f"- grid_mode    : {args.grid_mode}")
    print(f"- patch/stride : {args.patch_size}/{args.stride}")
    print(f"- mask_type    : {args.mask_type}")
    print(f"- min_fg_ratio : {args.min_foreground_ratio}")
    print(f"- augment      : {augment}")
    print(f"- brightness   : {brightness_range}")
    print(f"- contrast     : {contrast_range}")
    print(f"- weight_decay : {args.weight_decay}")
    print(f"- fov_mask     : {args.use_fov_mask}")
    print(f"- fov_thr      : {args.fov_threshold}")
    print(f"- fov_blur     : {args.fov_blur}")
    print(f"- fov_close    : {args.fov_close}")
    print(f"- fov_min_ratio: {args.fov_min_ratio}")
    print(f"- loss_type    : {args.loss_type}")
    if args.loss_type == 'bce_dice':
        print(f"- bce/dice     : {args.bce_weight}/{args.dice_weight}")
    else:
        print(f"- tversky a/b  : {args.tversky_alpha}/{args.tversky_beta}")
        if args.loss_type == 'focal_tversky':
            print(f"- tversky gamma: {args.tversky_gamma}")
    if args.grid_mode:
        print(f"- lambda_list  : {args.lambda_list}")
    else:
        print(f"- lambda_ds    : {args.lambda_ds}")
    print("#" * 70 + "\n")

    start_time_all = datetime.now()

    if args.grid_mode:
        lambda_list = parse_float_list(args.lambda_list)
        print(f"Grid mode lambda list: {lambda_list}")
        for i, lam in enumerate(lambda_list):
            print(f"\n==== Grid progress: {i + 1}/{len(lambda_list)}, lambda={lam:.2f} ====")
            train_single_lambda(lam, args, device, train_loader, val_loader)
    else:
        print(f"Single lambda mode: lambda={args.lambda_ds:.2f}")
        train_single_lambda(args.lambda_ds, args, device, train_loader, val_loader)

    duration_all = datetime.now() - start_time_all
    print("\n" + "=" * 60)
    print("CHASEDB1 training finished")
    print(f"Elapsed: {duration_all}")
    print("=" * 60)


if __name__ == '__main__':
    main()



